### ISSUE TITLE
Spit webite's pages

### ISSUE THREAD

**Issue by samuel20miglia** [cocconappteam/cocconapp.com#1]
split website's template from 1 single page to many pages how many links pointed over the div.

**Comment by DavideBiasin** [comment]
Maybe it's better keep one single page for now. 
For split to multiple page We need to review all website pages, it is not simply to split a single page template to multiple one. If in the future We will need more page We will can buy a new template or We can do a refactoring of this. 
For the moment the website serves only to advertise the app, then keep it in a single page layout I think is the best solution.

**Comment by samuel20miglia** [comment]
Ok, i agree
